# Generated by Django 4.2 on 2024-04-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_delete_post'),
        ('accounts', '0002_user_delete_liter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='choose_products',
            field=models.ManyToManyField(related_name='choose_users', to='products.product'),
        ),
    ]
